### ISSUE TITLE
1.11.2 Crash 

### ISSUE THREAD

**Issue by Kashdeya** [ThexXTURBOXx/MegaQuarry#1]
Forge version = 13.20.1.2388
Minecraft Version = 1.11.2
MegaQuarry Version = 1.3-1.11+

Single player loads up fine but when put on a server you get this crash

`java.lang.NullPointerException: The name to be added to the registry is null. This can only happen with a corrupted registry state. Reflection/ASM hackery? Registry bug?
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.addObjectRaw(FMLControlledNamespacedRegistry.java:574)
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.set(FMLControlledNamespacedRegistry.java:208)
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.loadRegistry(PersistentRegistryManager.java:419)
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.freezeData(PersistentRegistryManager.java:506)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:837)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:109)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:215)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Unknown Source)`

I had to downgrade to version 1.2.2-1.11+ to resolve the issue on my server.

**Comment by ThexXTURBOXx** [comment]
I have no idea, why it works on 1.2.2, but not on 1.3... There is no difference in those files (besides of the version numbers)...

**Comment by ThexXTURBOXx** [comment]
I close this issue, because I think, that it's not my mod, which causes this issue.
For me, everything works fine
